// var majorPairs = "EUR/USD,EUR/GBP,GBP/USD,EUR/CHF,USD/CAD,AUD/USD,USD/CHF,EUR/JPY,USD/JPY,GBP/JPY";
// var euroPairs = "EUR/AUD,EUR/CAD,EUR/CZK,EUR/DKK,EUR/HUF,EUR/NOK,EUR/NZD,EUR/PLN,EUR/SEK,EUR/TRY,EUR/SGD,EUR/ZAR";
// var usdPairs = "USD/CNH,USD/CZK,USD/DKK,USD/HKD,USD/HUF,USD/INR,USD/MXN,USD/NOK,USD/PLN,USD/SAR,USD/SEK,USD/SGD,USD/THB,USD/TRY,USD/ZAR";
// var otherPairs = "GBP/AUD,GBP/CAD,GBP/CHF,GBP/NZD,GBP/ZAR,GBP/PLN,GBP/SGD,AUD/CAD,AUD/JPY,AUD/NZD,AUD/SGD,CAD/CHF,CAD/JPY,CAD/SGD,CHF/JPY,CHF/ZAR,NZD/CAD,NZD/JPY,NZD/USD,NZD/SGD,SGD/JPY,TRY/JPY,ZAR/JPY";
// var metalPairs = "XAG/JPY,XAG/USD,XAU/JPY,XAU/USD";
